[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend.render.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-backend.render.com"

[context.deploy-preview.environment]  
  VITE_API_URL = "https://your-backend.render.com"

[context.branch-deploy.environment]
  VITE_API_URL = "https://your-backend.render.com"
